### PR TITLE
French translation file added in Translations folder

### PR DESCRIPTION
**Pull request by Sieste68**

### CODE REVIEW

**Review by marcopal74 — APPROVED** [review]
Thank you very much for your contribution! 👍🏻
Please give me a feedback about the integration in order to improve the experience.

**Comment by Sieste68** [comment]
A copy-paste of the folder inside the custom_components is quiet easy to do, the restart HA.
After that, I moved to configuration->integration->add and search for Palazzetti.
2 devices have been found: the CBox and the hoven. I didn't map the CBox but its IP address in important to know.
I have the Anna model with 3 fans.
About that, there is some other "words" to translate. I will path through all files to find them like:
- temp. Ambiente
- Potenza
- Main Fan
- Fan L & Fan R
- Pellet Consommato
- Product
- Silent
All these keywords are not in the translation file. May it should be nice to switch them in it (some work to do ;-) ).
I was also able to update the Main Fan and Fire Power (Potenza, I assume).

Also, and not the latest, I had to switch from a Docker installation to a Raspberry Pi to let it working correctly. No way to reach the CBox under Docker installation, so, no container version.

**Comment by marcopal74** [comment]
Thank you very much, I must admit I've been lazy with translations ;-)
For the Docker installation: I'm using HA from a Docker into a Synology NAS and works perfectly but remember to setup the network in "host" mode and not "bridge". If you can access the bash of the terminal please check if you can ping the IP of the CBox, if so and the integration doesn't work please let me know, there are a couple of things we can try.
Thank you again.

**Comment by Sieste68** [comment]
No problem about translation, if I can help ;-)
I have also a Synology NAS, but I switch to a rapsberry the home assistant because I had some issues with other devices.
I'm just starting in Home Assistant things and world. 
Anyway, if you're able to push these words inside the translation file (en or it), I should be able to make the french translation. For sure, it will require an update later
I didn't integrate the sensor, yet because I don't know yet how it works and how to integrate it. I move slowly on HA world,
Here is a screenshot of the minimal insertion in HA. I have an Anna model.

image

**Pull request merged**
